<?php

namespace sborislav\ApiBundle\Repository;

/**
 * GrouppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
}
